title: SETI.news
tagline: The latest in SETI research
description: A newsletter collecting the latest in academic SETI research.
url: https://SETI.news
baseurl: ""
paginate: 5
paginate_path: "/page:num/"
permalink: pretty

author:
  name: James R. A. Davenport
  url: https://twitter.com/jradavenport
  email: jrad@uw.edu

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

version: 2.0.0
google_analytics_id:
logo: /public/s.png
